x-logging: &default-logging
    driver: json-file
    options:
        max-size: 50m
        max-file: 5
        compress: 1

services:

  backend:
    image: mhz19-go-backend
    env_file: .env
    volumes:
      - ./sqlite:/app/sqlite
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    logging: *default-logging
    depends_on:
      - mosquitto

  frontend:
    build:
      context: ../mhz19-front
    image: mhz19-front
    env_file: ".env"
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - backend
    ports:
      - 7171:80

  device-pinger:
    build:
      context: ../device-pinger
    image: device-pinger
    env_file: ".env"
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - mosquitto
    ports:
      - 2112:2112

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    ports:
      - 7000:7000
    volumes:
      - ./zigbee2mqtt-data:/app/data
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      - mosquitto
    restart: unless-stopped
    logging: *default-logging
    environment:
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=/dev/ttyUSB0
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://mosquitto
      - ZIGBEE2MQTT_CONFIG_MQTT_USER=mosquitto
      - ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD=$MQTT_PASSWORD

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
    restart: unless-stopped
    logging: *default-logging
    command: |
      /bin/sh -c "
          mkdir -p /etc/mosquitto && touch /etc/mosquitto/passwd && mosquitto_passwd -b /etc/mosquitto/passwd $MQTT_USERNAME $MQTT_PASSWORD && /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf
      "

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9092:9090
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-admin-api
    extra_hosts:
      - host.docker.internal:host-gateway
    logging: *default-logging      

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3002:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage:
  prometheus_data: