global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: backend 
    static_configs:
      - targets:
        - host.docker.internal:7070
  - job_name: device-pinger
    static_configs:
      - targets:
        - host.docker.internal:2112
  - job_name: macmini
    static_configs:
      - targets:
        - 192.168.88.188:9100
  - job_name: rpi
    static_configs:
      - targets:
        - 192.168.88.40:9100