{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mhz19_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rules executed" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mhz19_rules)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Requests By Method",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mhz19_api_requests", "legendFormat": "{{method}} {{path}}" }
   ]
  },
  {
   "title": "Rules Executed Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mhz19_rules", "legendFormat": "{{rule_name}}" }
   ]
  },
  {
   "title": "Heap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gorutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Messages By Channel",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mhz19_messages_by_channel", "legendFormat": "{{channel}}" }
   ]
  },
  {
   "title": "Errors by module",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mhz19_errors", "legendFormat": "{{module}}" }
   ]
  },
  {
   "title": "Average Transaction Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mhz19_transactions_sum/mhz19_transactions_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time for handleMessage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mhz19_messages_handled_sum / mhz19_messages_handled_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mhz19_transactions_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Messages handled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mhz19_messages_handled_count", "legendFormat": "__auto" }
   ]
  }
 ]
}