{
 "title": "Device Pinger",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"host.docker.internal:2112\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pinger_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Actions Executed",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (action) (pinger_actions_handled)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"host.docker.internal:2112\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gorutines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"host.docker.internal:2112\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pinger_errors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Targets Monitored",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pinger_workers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MQTT Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pinger_mqtt_received", "legendFormat": "Received" },
    { "expr": "pinger_mqtt_published", "legendFormat": "Published" }
   ]
  }
 ]
}